"""empty message

Revision ID: 0d0cbea2e450
Revises: 111db127e634
Create Date: 2023-07-26 11:23:51.751470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0cbea2e450'
down_revision = '111db127e634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('List of orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('List of orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
